# Generated by Django 2.1 on 2018-08-09 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot_Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeslots_app.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot_Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeslots_app.Interviewer')),
            ],
        ),
    ]
