# Generated by Django 2.1 on 2018-08-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots_app', '0002_timeslot_candidate_timeslot_interviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot_candidate',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot_candidate',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot_interviewer',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot_interviewer',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
